### ISSUE TITLE
Could you upload the sql file please?

### ISSUE THREAD

**Issue by Gakaka** [arif98741/pos_git#21]
I like pure PHP and love your code. Could you please upload the sql file?

**Comment by arif98741** [comment]
from where you are talking. By the way, thanks for your interest in code.

**Comment by arif98741** [comment]
This is database file link. Use this. You may got some error as this is old project and have some issues also
[Pos Git Database File - Click Here](https://github.com/arif98741/pos_git/blob/database/database/db_pos_git.sql )

**Comment by Gakaka** [comment]
Thank you so much! I will try to handle it 😉

**Comment by arif98741** [comment]
I restructured and reformatted code in master branch. Please use the latest one again.

**Comment by Gakaka** [comment]
So kind of you to do that, thanks again!
